services:
    mongodb:
        image: mongo:latest
        container_name:mongodb_UI
        hostname: db
        volumes:
        "define volume mappings for the mongodb service"
            - mongodb_data:/data/db
            - ./mongodb.env:/etc/mongodb.env
        env_file:
            - .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWPORD}
        ports:
            - "27017:27017"
        networks:
            - mongodb_network
        depends_on:
            - mongodb
    
    utils:
      build:
        context: .
        dockerfile: Dockerfile
      volumnes:
        - ./utils:/utils

        "The volumes section in the Docker Compose file maps local files from your host machine
         to specific paths within the container where the service is running. 
         This mapping allows users to update and use these files within the container 
         without rebuilding the image"

networks:
"defines a custom network: allow containers to communicate with each other"
    mongodb_network:
        driver: bridge

volumes:
"persist data generated by containers 
ensure that data stored by services using this volume remains available 
even if the containers are stopped or removed"
    mongodb_data:
        driver: local




        
