services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_UI
    hostname: db
    volumes:
      - mongodb_data:/data/db
      - ./mongodb.env:/etc/mongodb.env
    env_file:
      - mongodb.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - mongodb_network
    depends_on:
      - utils

  utils:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./utils:/utils

networks:
  mongodb_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local




        
